/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_webcrawler_osori_opencvhog_MainActivity */

#ifndef _Included_android_webcrawler_osori_opencvhog_MainActivity
#define _Included_android_webcrawler_osori_opencvhog_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_webcrawler_osori_opencvhog_MainActivity
 * Method:    convertNativeGray
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_android_webcrawler_osori_opencvhog_MainActivity_loadCascade
  (JNIEnv *, jobject);

/*
 * Class:     android_webcrawler_osori_opencvhog_MainActivity
 * Method:    calcOpticalFlow
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_android_webcrawler_osori_opencvhog_MainActivity_calcOpticalFlow
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     android_webcrawler_osori_opencvhog_MainActivity
 * Method:    hogDetection
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_android_webcrawler_osori_opencvhog_MainActivity_hogDetection
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
